import type { Metadata } from "next";
import AuthProvider from "@/components/common/AuthProvider";
import "./globals.css";
import Header from "@/components/common/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getInitialAuth = async () => {
  // 서버에서 사용자 정보를 가져오는 로직
  return {
    initialAccessToken: null,
    initialUser: null,
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Whhiskyrail</title>
      </head>
      <body
      
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
