import type { Metadata } from "next";
import { cookies } from "next/headers";
import Header from "@/components/common/Header";
import AuthInitializer from "@/libs/common/AuthInitializer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let initUser = null;
  let initAccessToken = null;
  const cookieStore = cookies();
  const cookieHeader = (await cookieStore).toString();
  try {
    const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/refresh`, {
      method: "POST",
      headers: {
        Cookie: cookieHeader,
      },
    });
    if (res.ok) {
      const { data } = await res.json();
      if (data) {
        initUser = data.payload;
        initAccessToken = data.accessToken;
      }
    }
  } catch (error) {
    console.error(error);
  }

  return (
    <html lang="ko">
      <head>
        <title>Whhiskyrail</title>
      </head>
      <body>
        <AuthInitializer
          initUser={initUser}
          initAccessToken={initAccessToken}
        />
        <Header initUser={initUser} initAccessToken={initAccessToken} />
        {children}
      </body>
    </html>
  );
}
